//
//  GaussianMassModel.swift
//  QRTL Gravity Lense
//
//  Extended 3-D Gaussian mass distribution.
//
//  Primary configuration:
//      1,000,000 solar masses
//
//  normalizedDensity() is dimensionless and is for field/surface
//  visualization.
//
//  gravitationalAcceleration() is physically mass-scaled and is
//  intended to drive photon gravitational curvature.
//

import Foundation
import simd

struct GaussianMassModel {

    // ============================================================
    // PHYSICAL CONSTANTS
    // ============================================================

    static let gravitationalConstant =
        6.67430e-11

    static let solarMass =
        1.98847e30

    // ============================================================
    // MASS MODEL
    // ============================================================

    /// Total mass in kilograms.
    let totalMass: Double

    /// Gaussian sigma / characteristic radius in meters.
    let characteristicRadius: Double

    // ============================================================
    // INITIALIZATION
    // ============================================================

    init(
        totalMass: Double,
        characteristicRadius: Double
    ) {

        self.totalMass =
            max(
                totalMass,
                0.0
            )

        self.characteristicRadius =
            max(
                characteristicRadius,
                1.0e-6
            )
    }

    // ============================================================
    // ONE-MILLION-SOLAR-MASS CLUSTER
    // ============================================================

    init(
        millionSolarMassClusterRadius radius: Double
    ) {

        self.init(
            totalMass:
                1_000_000.0 *
                Self.solarMass,

            characteristicRadius:
                radius
        )
    }

    // ============================================================
    // MASS IN SOLAR MASSES
    // ============================================================

    var totalMassSolarMasses: Double {

        totalMass /
        Self.solarMass
    }

    // ============================================================
    // 3-D GAUSSIAN MASS DENSITY
    //
    // rho(r) =
    //
    // M / ((2*pi)^(3/2) * sigma^3)
    //
    // * exp(-r^2 / (2*sigma^2))
    //
    // Units: kg / m^3
    // ============================================================

    func density(
        at position: SIMD3<Double>
    ) -> Double {

        let sigma =
            characteristicRadius

        let radiusSquared =
            simd_length_squared(
                position
            )

        let normalization =
            totalMass /
            (
                pow(
                    2.0 * Double.pi,
                    1.5
                )
                *
                pow(
                    sigma,
                    3.0
                )
            )

        let exponent =
            -radiusSquared /
            (
                2.0 *
                sigma *
                sigma
            )

        let value =
            normalization *
            exp(exponent)

        guard value.isFinite else {
            return 0.0
        }

        return max(
            value,
            0.0
        )
    }

    // ============================================================
    // NORMALIZED DENSITY
    //
    // Center = 1
    // Far away = 0
    //
    // IMPORTANT:
    // This deliberately removes the physical mass scale.
    // Do NOT use this function by itself to calculate gravity.
    // ============================================================

    func normalizedDensity(
        at position: SIMD3<Double>
    ) -> Double {

        let sigma =
            characteristicRadius

        let radiusSquared =
            simd_length_squared(
                position
            )

        let exponent =
            -radiusSquared /
            (
                2.0 *
                sigma *
                sigma
            )

        let value =
            exp(exponent)

        guard value.isFinite else {
            return 0.0
        }

        return min(
            max(
                value,
                0.0
            ),
            1.0
        )
    }

    // ============================================================
    // ENCLOSED MASS
    //
    // The Gaussian is an extended spherical distribution.
    //
    // The gravitational field at radius r is generated by the
    // mass enclosed inside that radius.
    // ============================================================

    func enclosedMass(
        at position: SIMD3<Double>
    ) -> Double {

        let radius =
            simd_length(
                position
            )

        guard
            radius.isFinite,
            radius > 0.0,
            totalMass > 0.0
        else {
            return 0.0
        }

        let sigma =
            characteristicRadius

        let x =
            radius /
            (
                sqrt(2.0) *
                sigma
            )

        let exponentialTerm =
            sqrt(
                2.0 /
                Double.pi
            )
            *
            (
                radius /
                sigma
            )
            *
            exp(
                -radius * radius /
                (
                    2.0 *
                    sigma *
                    sigma
                )
            )

        let fraction =
            erf(x) -
            exponentialTerm

        guard fraction.isFinite else {
            return 0.0
        }

        return totalMass *
            min(
                max(
                    fraction,
                    0.0
                ),
                1.0
            )
    }

    // ============================================================
    // PHYSICAL GRAVITATIONAL ACCELERATION
    //
    // This is the important function for QRTLPhotonTracer.
    //
    // The acceleration points toward the center of the cluster.
    //
    // Units:
    //      meters / second^2
    //
    // This contains the actual 1,000,000-solar-mass scale.
    // ============================================================

    func gravitationalAcceleration(
        at position: SIMD3<Double>
    ) -> SIMD3<Double> {

        let radius =
            simd_length(
                position
            )

        guard
            radius.isFinite,
            radius > 1.0e-12,
            totalMass > 0.0
        else {
            return .zero
        }

        let massInside =
            enclosedMass(
                at: position
            )

        guard
            massInside.isFinite,
            massInside > 0.0
        else {
            return .zero
        }

        let magnitude =
            Self.gravitationalConstant *
            massInside /
            (
                radius *
                radius
            )

        guard magnitude.isFinite else {
            return .zero
        }

        let directionToCenter =
            -position /
            radius

        let acceleration =
            directionToCenter *
            magnitude

        guard
            acceleration.x.isFinite,
            acceleration.y.isFinite,
            acceleration.z.isFinite
        else {
            return .zero
        }

        return acceleration
    }

    // ============================================================
    // GRAVITATIONAL POTENTIAL
    //
    // Used by the QRTL gravity-surface / metric pipeline.
    //
    // For the spherical Gaussian distribution:
    //
    // Phi(r) =
    //
    // -G*M*erf(r/(sqrt(2)*sigma)) / r
    //
    // The center uses the finite Gaussian limit.
    // ============================================================

    func gravitationalPotential(
        at position: SIMD3<Double>
    ) -> Double {

        let radius =
            simd_length(
                position
            )

        guard
            radius.isFinite,
            totalMass > 0.0
        else {
            return 0.0
        }

        let sigma =
            characteristicRadius

        if radius < 1.0e-12 {

            return
                -Self.gravitationalConstant
                *
                totalMass
                *
                sqrt(
                    2.0 /
                    Double.pi
                )
                /
                sigma
        }

        let x =
            radius /
            (
                sqrt(2.0) *
                sigma
            )

        let potential =
            -Self.gravitationalConstant
            *
            totalMass
            *
            erf(x)
            /
            radius

        guard potential.isFinite else {
            return 0.0
        }

        return potential
    }

    // ============================================================
    // SCHWARZSCHILD RADIUS
    //
    // Diagnostic only.
    // ============================================================

    var schwarzschildRadius: Double {

        let c =
            299_792_458.0

        return
            2.0
            *
            Self.gravitationalConstant
            *
            totalMass
            /
            (c * c)
    }
}
