//
//  File.swift
//  QRTL Gravity Lense
//
//  Created by David Nishimoto on 8/18/26.
//

import Foundation
import simd

// ============================================================
// QRTL FIELD
// ============================================================

final class QRTLField {

    let massModel: GaussianMassModel
    let parameters: QRTLParameters
    let referenceDensity: Float

    init(
        massModel: GaussianMassModel,
        parameters: QRTLParameters
    ) {

        self.massModel = massModel
        self.parameters = parameters

        let centerDensity =
            massModel.density(
                at: .zero
            )

        self.referenceDensity =
            max(
                Float(centerDensity),
                0.000001
            )
    }


    // =========================================================
    // FIELD SAMPLE
    //
    // This is the single unified field state used by
    // tracePhoton().
    // =========================================================

    struct Sample {

        let massDensity: Float

        let normalizedDensity: Float

        let qrtlSource: Float

        let bolgarinoFlux: SIMD3<Float>

        let qrtlCurrentDensity: SIMD3<Float>

        let qrtlCurrent: Float

        let magneticField: SIMD3<Float>

        let magneticEnergyDensity: Float

        let qrtlEnergyDensity: Float

        let effectiveEnergyDensity: Float

        let gravitationalPotential: Float

        let gravitationalIndex: Float

        let electromagneticIndex: Float

        let totalIndex: Float
    }


    // =========================================================
    // MASS DENSITY
    // =========================================================

    func massDensity(
        at position: SIMD3<Float>
    ) -> Float {

        let p =
            SIMD3<Double>(
                Double(position.x),
                Double(position.y),
                Double(position.z)
            )

        let density =
            Float(
                massModel.density(
                    at: p
                )
            )

        guard density.isFinite else {
            return 0.0
        }

        return max(
            density,
            0.0
        )
    }


    // =========================================================
    // NORMALIZED MASS DENSITY
    // =========================================================

    func normalizedDensity(
        at position: SIMD3<Float>
    ) -> Float {

        let density =
            massDensity(
                at: position
            )

        let normalized =
            density /
            referenceDensity

        guard normalized.isFinite else {
            return 0.0
        }

        return min(
            max(
                normalized,
                0.0
            ),
            1.0
        )
    }


    // =========================================================
    // QRTL / GRAVITY-LIKE INFLUENCE
    //
    // Inward influence generated by the QRTL source.
    // =========================================================

    func influence(
        at position: SIMD3<Float>
    ) -> SIMD3<Float> {

        let radius =
            simd_length(
                position
            )

        guard radius.isFinite,
              radius > 0.000001
        else {
            return .zero
        }

        let inwardDirection =
            -position / radius

        let density =
            normalizedDensity(
                at: position
            )

        let distanceFalloff =
            1.0 /
            max(
                radius * radius,
                0.01
            )

        let strength =
            Float(parameters.alphaQ) *
            density *
            distanceFalloff

        guard strength.isFinite else {
            return .zero
        }

        return inwardDirection *
            strength
    }


    // =========================================================
    // QRTL SOURCE
    //
    // Baryonic density -> QRTL source.
    // =========================================================

    func qrtlSource(
        at position: SIMD3<Float>
    ) -> Float {

        let density =
            normalizedDensity(
                at: position
            )

        let source =
            Float(parameters.alphaQ) *
            density

        guard source.isFinite else {
            return 0.0
        }

        return max(
            source,
            0.0
        )
    }


    // =========================================================
    // BOLGARINO / QRTL RADIAL FLOW
    //
    // The source generates an outward radial QRTL flux.
    // =========================================================

    func bolgarinoFlux(
        at position: SIMD3<Float>
    ) -> SIMD3<Float> {

        let radius =
            simd_length(
                position
            )

        guard radius.isFinite,
              radius > 0.000001
        else {
            return .zero
        }

        let radialDirection =
            position / radius

        let source =
            qrtlSource(
                at: position
            )

        let falloff =
            1.0 /
            max(
                radius * radius,
                0.01
            )

        let fluxMagnitude =
            source *
            falloff

        guard fluxMagnitude.isFinite else {
            return .zero
        }

        return radialDirection *
            fluxMagnitude
    }


    // =========================================================
    // QRTL CURRENT DENSITY
    //
    // QRTL flux -> current density.
    //
    // This is the critical new causal link.
    // =========================================================

    func qrtlCurrentDensity(
        at position: SIMD3<Float>
    ) -> SIMD3<Float> {

        let flux =
            bolgarinoFlux(
                at: position
            )

        let coupling =
            Float(
                parameters.electromagneticCoupling
            )

        let currentDensity =
            flux *
            coupling

        guard currentDensity.x.isFinite,
              currentDensity.y.isFinite,
              currentDensity.z.isFinite
        else {
            return .zero
        }

        return currentDensity
    }


    // =========================================================
    // QRTL CURRENT
    // =========================================================

    func qrtlCurrent(
        at position: SIMD3<Float>
    ) -> Float {

        let currentDensity =
            qrtlCurrentDensity(
                at: position
            )

        let current =
            simd_length(
                currentDensity
            )

        guard current.isFinite else {
            return 0.0
        }

        return current
    }


    // =========================================================
    // QRTL MAGNETIC FIELD
    //
    // Current generates the electromagnetic field.
    //
    // For a radial current, the physically appropriate
    // surrounding field is represented as a tangential/
    // azimuthal field rather than another arbitrary radial
    // field.
    // =========================================================

    func magneticField(
        at position: SIMD3<Float>
    ) -> SIMD3<Float> {

        let radius =
            simd_length(
                position
            )

        guard radius.isFinite,
              radius > 0.000001
        else {
            return .zero
        }

        let currentDensity =
            qrtlCurrentDensity(
                at: position
            )

        let current =
            simd_length(
                currentDensity
            )

        guard current.isFinite,
              current > 0.0
        else {
            return .zero
        }

        // -----------------------------------------------------
        // Define a stable azimuthal direction.
        // The QRTL radial flow creates a surrounding field.
        // -----------------------------------------------------

        let radial =
            position / radius

        let referenceAxis =
            SIMD3<Float>(
                0.0,
                1.0,
                0.0
            )

        var tangent =
            simd_cross(
                referenceAxis,
                radial
            )

        // If the radial direction is nearly parallel to the
        // reference axis, use X as the fallback axis.
        if simd_length_squared(tangent) < 0.000001 {

            tangent =
                simd_cross(
                    SIMD3<Float>(
                        1.0,
                        0.0,
                        0.0
                    ),
                    radial
                )
        }

        let tangentLength =
            simd_length(
                tangent
            )

        guard tangentLength > 0.000001 else {
            return .zero
        }

        tangent /=
            tangentLength

        // -----------------------------------------------------
        // Current -> magnetic field.
        //
        // This remains an effective QRTL coupling until the
        // QRTL theory supplies a derived coupling constant.
        // -----------------------------------------------------

        let coupling =
            Float(
                parameters.electromagneticCoupling
            )

        let fieldStrength =
            coupling *
            current /
            max(
                radius,
                0.01
            )

        guard fieldStrength.isFinite else {
            return .zero
        }

        return tangent *
            fieldStrength
    }


    // =========================================================
    // MAGNETIC ENERGY DENSITY
    // =========================================================

    func magneticEnergyDensity(
        at position: SIMD3<Float>
    ) -> Float {

        let field =
            magneticField(
                at: position
            )

        let bSquared =
            simd_length_squared(
                field
            )

        guard bSquared.isFinite else {
            return 0.0
        }

        let mu0 =
            Float(
                PhysicalConstants.mu0
            )

        guard mu0 > 0.0 else {
            return 0.0
        }

        let energy =
            bSquared /
            (2.0 * mu0)

        guard energy.isFinite else {
            return 0.0
        }

        return max(
            energy,
            0.0
        )
    }


    // =========================================================
    // QRTL ENERGY DENSITY
    // =========================================================

    func qrtlEnergyDensity(
        at position: SIMD3<Float>
    ) -> Float {

        let source =
            qrtlSource(
                at: position
            )

        let flux =
            bolgarinoFlux(
                at: position
            )

        let fluxMagnitude =
            simd_length(
                flux
            )

        let energy =
            source *
            fluxMagnitude

        guard energy.isFinite else {
            return 0.0
        }

        return max(
            energy,
            0.0
        )
    }


    // =========================================================
    // GRAVITATIONAL POTENTIAL
    //
    // Weak-field effective potential used by the optical
    // index calculation.
    // =========================================================

    func gravitationalPotential(
        at position: SIMD3<Float>,
        effectiveEnergyDensity: Float
    ) -> Float {

        let radius =
            simd_length(
                position
            )

        guard radius.isFinite,
              radius > 0.000001
        else {
            return 0.0
        }

        let effectiveMassDensity =
            effectiveEnergyDensity /
            Float(
                PhysicalConstants.c *
                PhysicalConstants.c
            )

        let density =
            massDensity(
                at: position
            )

        let totalDensity =
            density +
            effectiveMassDensity

        let G =
            Float(
                PhysicalConstants.G
            )

        let potential =
            -G *
            totalDensity *
            radius

        guard potential.isFinite else {
            return 0.0
        }

        return potential
    }


    // =========================================================
    // ELECTROMAGNETIC OPTICAL CONTRIBUTION
    // =========================================================

    func electromagneticOpticalContribution(
        at position: SIMD3<Float>
    ) -> Float {

        let energy =
            magneticEnergyDensity(
                at: position
            )

        guard energy.isFinite else {
            return 0.0
        }

        return energy
    }


    // =========================================================
    // COMPLETE FIELD SAMPLE
    //
    // This is what tracePhoton() calls.
    // =========================================================

    func sample(
        at position: SIMD3<Float>
    ) -> Sample {

        let density =
            massDensity(
                at: position
            )

        let normalized =
            normalizedDensity(
                at: position
            )

        let source =
            qrtlSource(
                at: position
            )

        let flux =
            bolgarinoFlux(
                at: position
            )

        let currentDensity =
            qrtlCurrentDensity(
                at: position
            )

        let current =
            simd_length(
                currentDensity
            )

        let magnetic =
            magneticField(
                at: position
            )

        let magneticEnergy =
            magneticEnergyDensity(
                at: position
            )

        let qrtlEnergy =
            qrtlEnergyDensity(
                at: position
            )

        let effectiveEnergy =
            qrtlEnergy +
            magneticEnergy

        let potential =
            gravitationalPotential(
                at: position,
                effectiveEnergyDensity:
                    effectiveEnergy
            )

        // -----------------------------------------------------
        // GR/QRTL gravitational optical index
        //
        // gammaQ = 1 reproduces the weak-field GR coefficient.
        // -----------------------------------------------------

        let cSquared =
            Float(
                PhysicalConstants.c *
                PhysicalConstants.c
            )

        let gamma =
            Float(
                parameters.gammaQ
            )

        let gravitationalIndex =
            1.0 -
            (1.0 + gamma) *
            potential /
            cSquared

        // -----------------------------------------------------
        // EM optical contribution
        // -----------------------------------------------------

        let photonCoupling =
            Float(
                parameters.photonEMCoupling
            )

        let electromagneticIndex =
            1.0 +
            photonCoupling *
            electromagneticOpticalContribution(
                at: position
            )

        // -----------------------------------------------------
        // TOTAL INDEX
        //
        // The photon sees ONE combined index.
        // -----------------------------------------------------

        let totalIndex =
            gravitationalIndex *
            electromagneticIndex

        return Sample(

            massDensity:
                density,

            normalizedDensity:
                normalized,

            qrtlSource:
                source,

            bolgarinoFlux:
                flux,

            qrtlCurrentDensity:
                currentDensity,

            qrtlCurrent:
                current,

            magneticField:
                magnetic,

            magneticEnergyDensity:
                magneticEnergy,

            qrtlEnergyDensity:
                qrtlEnergy,

            effectiveEnergyDensity:
                effectiveEnergy,

            gravitationalPotential:
                potential,

            gravitationalIndex:
                gravitationalIndex,

            electromagneticIndex:
                electromagneticIndex,

            totalIndex:
                totalIndex
        )
    }


    // =========================================================
    // TOTAL INDEX GRADIENT
    //
    // Numerical central-difference gradient of the SAME
    // totalIndex returned by sample(at:).
    // =========================================================

    func indexGradient(
        at position: SIMD3<Float>
    ) -> SIMD3<Float> {

        let radius =
            max(
                simd_length(position),
                1.0
            )

        let h =
            max(
                radius * 0.001,
                0.0001
            )

        let xPlus =
            sample(
                at:
                    position +
                    SIMD3<Float>(
                        h,
                        0.0,
                        0.0
                    )
            ).totalIndex

        let xMinus =
            sample(
                at:
                    position -
                    SIMD3<Float>(
                        h,
                        0.0,
                        0.0
                    )
            ).totalIndex

        let yPlus =
            sample(
                at:
                    position +
                    SIMD3<Float>(
                        0.0,
                        h,
                        0.0
                    )
            ).totalIndex

        let yMinus =
            sample(
                at:
                    position -
                    SIMD3<Float>(
                        0.0,
                        h,
                        0.0
                    )
            ).totalIndex

        let zPlus =
            sample(
                at:
                    position +
                    SIMD3<Float>(
                        0.0,
                        0.0,
                        h
                    )
            ).totalIndex

        let zMinus =
            sample(
                at:
                    position -
                    SIMD3<Float>(
                        0.0,
                        0.0,
                        h
                    )
            ).totalIndex

        let gradient =
            SIMD3<Float>(
                (xPlus - xMinus) /
                    (2.0 * h),

                (yPlus - yMinus) /
                    (2.0 * h),

                (zPlus - zMinus) /
                    (2.0 * h)
            )

        guard gradient.x.isFinite,
              gradient.y.isFinite,
              gradient.z.isFinite
        else {
            return .zero
        }

        return gradient
    }


    // =========================================================
    // EXISTING ELECTROMAGNETIC INFLUENCE
    //
    // Kept as a compatibility function.
    //
    // IMPORTANT:
    // It now comes from the QRTL magnetic field/current
    // instead of independently inventing an EM field from
    // density.
    // =========================================================

    func electromagneticInfluence(
        at position: SIMD3<Float>
    ) -> SIMD3<Float> {

        let magnetic =
            magneticField(
                at: position
            )

        let coupling =
            Float(
                parameters.photonEMCoupling
            )

        let influence =
            magnetic *
            coupling

        guard influence.x.isFinite,
              influence.y.isFinite,
              influence.z.isFinite
        else {
            return .zero
        }

        return influence
    }
}

